kind: Deployment
apiVersion: apps/v1
metadata:
  name: torch-build
  labels:
    app: torch-build
spec:
  replicas: 1
  selector:
    matchLabels:
      app: torch-build
      app.kubernetes.io/part-of: torch-build
      deployment: torch-build
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: torch-build
        app.kubernetes.io/part-of: torch-build
        deployment: torch-build
    spec:
      containers:
        - resources:
            limits:
              cpu: '12'
              memory: 32768Mi
            requests:
              cpu: '10'
              memory: 32768Mi
          name: run
          imagePullPolicy: IfNotPresent
          image: 'quay.io/centos/centos:stream8'
          volumeMounts:
            - mountPath: /opt/apps/easybuild
              name: easybuild-data
          command:
            - /opt/app-root/src/easybuild_run.sh
      volumes:
        - name: easybuild-data
          persistentVolumeClaim:
            claimName: easybuild-data
      terminationGracePeriodSeconds: 30
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600